### PR TITLE
Fix bold tags

### PR DESCRIPTION
**Pull request by ShauryaSen**

### CODE REVIEW

**Comment by Sam-Belliveau** [comment]
LGTM 🚀🚀🚀

**Review by Sam-Belliveau — APPROVED** [review]

**Comment by BenG49** [comment]
lgtm

**Comment by vincentw921** [comment]
LGTM 🤌🤌🤌🤌

**Review by BenG49 — APPROVED** [review]

**Comment by thunder-red-star** [comment]
@ShauryaSen where is your live deployment?!?!! how am i supposed to review your code? 😭

**Comment by novillo-cs** [comment]
Fixed!

**Pull request closed without merging**
